{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1554.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Orders\",\"Returns\",\"Manegers\",\"orders by region\",\"Dim Customer\",\"Dim Product\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "7198f2e9-8303-4d5a-bf76-4228ccd393e2",
        "fromColumn": "Order Date",
        "fromTable": "Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_13ba13e1-1c0a-4d7a-a659-963078043f92"
      },
      {
        "name": "d1de0896-5739-4878-86b0-e627540dba3f",
        "fromColumn": "Ship Date",
        "fromTable": "Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1ed80c1e-62ce-4830-b5cb-584a3e26f927"
      },
      {
        "name": "fe1a9eea-d684-4e2c-b014-758249e02845",
        "fromColumn": "Region",
        "fromTable": "Orders",
        "toColumn": "Region",
        "toTable": "Manegers"
      },
      {
        "name": "fcd3fee3-fb66-40c0-a217-60a24761b81d",
        "fromColumn": "Order Date",
        "fromTable": "orders by region",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_05447a49-6a11-4d7a-b5c2-9344940f2fdd"
      },
      {
        "name": "1d455758-9a79-4bec-83e9-e84f847f14ba",
        "fromColumn": "Ship Date",
        "fromTable": "orders by region",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_aa0949e3-1ac4-42a9-93c5-098404b2560b"
      },
      {
        "name": "0346320e-e7f5-4b0a-b079-af1a77cec5e0",
        "fromColumn": "Region",
        "fromTable": "orders by region",
        "toColumn": "Region",
        "toTable": "Manegers"
      },
      {
        "name": "5d55ecf4-8daf-4693-9787-bbcb80946526",
        "fromColumn": "Region",
        "fromTable": "Dim Customer",
        "toColumn": "Region",
        "toTable": "Manegers"
      },
      {
        "name": "217f691b-1b35-4d4f-aa6d-2556901d686a",
        "fromColumn": "Order ID",
        "fromTable": "Orders",
        "toColumn": "Order ID",
        "toTable": "Returns"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_12d3e879-fd60-416e-ac15-b87ec9a576f8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "933b976b-c305-40f7-9491-9b78d955fbef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0322d74a-2a3e-4f62-8b63-97fe3adfa6cb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3ab468f5-754f-4f82-bdac-120503bed946",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "76d78e10-1202-4591-9f89-e52c146fd865",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8113822f-7077-4f4c-90e9-e3ace35f56d7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5b6ffa70-b008-4131-897e-3fa6a79225e1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2b4d90a2-de71-42e6-b151-cd048cd885b5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "66254e92-6ec8-4e08-9dd6-02a848c95f6d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2133a193-43fb-4015-9a22-29bf3b1292e3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4110e973-efbe-4e46-940e-9ca1099fd88e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2d411411-c42b-4203-a563-7481882bc716",
                "ordinal": 3
              }
            ],
            "lineageTag": "227bbdd7-a120-4476-9d84-ea46c7adace4"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9473d5cf-9cb9-4eeb-9f5c-8627bf34a829",
        "partitions": [
          {
            "name": "DateTableTemplate_12d3e879-fd60-416e-ac15-b87ec9a576f8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "c450d986-fb7b-4955-b924-3c6ca08ea0c6",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1be4e0a5-16df-4298-94b7-deb301d451dd",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dbf1fb80-a775-4fdf-8f1b-8310a583b832",
            "sourceColumn": "Shipping Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7ee3a7a-9275-40f6-a14e-b46869027f9a",
            "sourceColumn": "Customer ID",
            "summarizeBy": "count"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9891990-f5fb-4e3b-9e05-819745fe7d0b",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "114199d3-97eb-4e1d-885b-59dbc5b5bfc1",
            "sourceColumn": "Ship Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "544a131c-ac07-44f5-8307-42062cc28dac",
            "sourceColumn": "Customer Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d7a7908-de1b-4ff6-ad3e-dc99da9f87db",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c0ba6dc-b3cb-476e-a5d1-7fda35f7d100",
            "sourceColumn": "Product Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Container",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37beabc7-8873-4fef-a0e4-b2ce5417f242",
            "sourceColumn": "Product Container",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36619b1d-63e5-48cf-9469-d6aa71e0ca55",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e7f6ae4-9f3c-4867-a4ae-998efbdaac97",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "29c4263e-a436-48df-8f55-0d76b1ea8983",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "a8ce5580-23a0-42ed-a812-38591fd3e88e",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "42691324-2c84-4e92-b8cc-227d7ed07c2a",
            "sourceColumn": "Postal Code",
            "summarizeBy": "count"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "42efa73d-045d-4f09-a7e7-d7f6c6470640",
            "sourceColumn": "Order Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_13ba13e1-1c0a-4d7a-a659-963078043f92"
                },
                "isDefault": true,
                "relationship": "7198f2e9-8303-4d5a-bf76-4228ccd393e2"
              }
            ]
          },
          {
            "name": "Ship Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1b943a86-0f4b-4766-ad21-bd3ddbf314db",
            "sourceColumn": "Ship Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1ed80c1e-62ce-4830-b5cb-584a3e26f927"
                },
                "isDefault": true,
                "relationship": "d1de0896-5739-4878-86b0-e627540dba3f"
              }
            ]
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1267871c-90ae-4df1-9124-48999f915d6c",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c59c3081-4b32-49b8-bd99-32a6c319974f",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e97ddf5-d14a-4f34-b136-8a4e1e710f86",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Region Hierarchy",
            "levels": [
              {
                "name": "Region",
                "column": "Region",
                "lineageTag": "b1b6d241-a2e3-42a7-b3d3-bc68abb7f841",
                "ordinal": 0
              },
              {
                "name": "Sales",
                "column": "Sales",
                "lineageTag": "04a1900e-a962-4aaa-b0d4-e595b1269232",
                "ordinal": 1
              },
              {
                "name": "State",
                "column": "State",
                "lineageTag": "c24eb7c3-70e7-4ba2-9576-3f58b83a9bea",
                "ordinal": 2
              },
              {
                "name": "City",
                "column": "City",
                "lineageTag": "97475ba1-f097-4ac7-833a-fe82a1e9968f",
                "ordinal": 3
              },
              {
                "name": "Postal Code",
                "column": "Postal Code",
                "lineageTag": "f628e0ae-274d-4858-b1a4-909533364b7c",
                "ordinal": 4
              }
            ],
            "lineageTag": "48d8afc3-8eaf-44dc-91d1-bc73d6d03ab7"
          }
        ],
        "lineageTag": "e09e78ca-1998-4e9f-b326-338c7d6bba94",
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\USER\\Downloads\\Power BI Exercise Files\\Sample Superstore.xlsx\"), null, true),",
                "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Row ID\", Int64.Type}, {\"Order Priority\", type text}, {\"Discount\", type number}, {\"Unit Price\", type number}, {\"Shipping Cost\", type number}, {\"Customer ID\", Int64.Type}, {\"Customer Name\", type text}, {\"Ship Mode\", type text}, {\"Customer Segment\", type text}, {\"Product Category\", type text}, {\"Product Sub-Category\", type text}, {\"Product Container\", type text}, {\"Product Name\", type text}, {\"Product Base Margin\", type number}, {\"Region\", type text}, {\"State or Province\", type text}, {\"City\", type text}, {\"Postal Code\", Int64.Type}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Profit\", type number}, {\"Quantity ordered new\", Int64.Type}, {\"Sales\", type number}, {\"Order ID\", Int64.Type}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Discount\", \"Unit Price\", \"Shipping Cost\", \"Customer ID\", \"Customer Name\", \"Ship Mode\", \"Customer Segment\", \"Product Category\", \"Product Sub-Category\", \"Product Container\", \"Product Name\", \"Region\", \"State or Province\", \"City\", \"Postal Code\", \"Order Date\", \"Ship Date\", \"Profit\", \"Sales\", \"Order ID\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([State or Province] = \"Arizona\" or [State or Province] = \"California\" or [State or Province] = \"Florida\" or [State or Province] = \"New Jersey\" or [State or Province] = \"New York\")),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Filtered Rows\",{{\"State or Province\", Order.Ascending}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Sorted Rows\",{{\"State or Province\", \"State\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_13ba13e1-1c0a-4d7a-a659-963078043f92",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d2419864-75a5-4f3b-8ff5-5fca4a56970e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9f256163-966d-48e1-91d4-114b125dc00a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "17f92429-8e46-4028-968b-cd14da7f64b3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "89e7b359-4f9a-4e54-9038-23d5ad54ff50",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "694c7cfa-f893-4b45-9202-ddfd534e8fb8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1550f810-6b09-45f7-ba4c-27446ae3d25d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4d122047-00de-4c52-8174-7a9da000ec83",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8407e147-dbcc-4517-a10b-df6afd25ea00",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "64c30fa2-1ed4-49bc-b588-04e12877b37d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bdee8f5c-ccd8-4eff-93c2-7c94e2dca9eb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "52dc3399-fe6f-466b-b64e-ceca373456e0",
                "ordinal": 3
              }
            ],
            "lineageTag": "5f3d0de6-f2ce-4e38-820b-9065931bbf80"
          }
        ],
        "isHidden": true,
        "lineageTag": "75870d7c-bc5f-483a-9daf-37421ab193dc",
        "partitions": [
          {
            "name": "LocalDateTable_13ba13e1-1c0a-4d7a-a659-963078043f92",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Orders'[Order Date])), 1, 1), Date(Year(MAX('Orders'[Order Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_1ed80c1e-62ce-4830-b5cb-584a3e26f927",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1174a8f5-3f87-4008-9180-0daecbbdf36c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9dadcfe9-19d1-47a5-a8a2-cf3a11d783d2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4989fdfd-82d7-407a-8f5a-b90a9e7f410d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bf7e3d48-71c0-406c-874d-b2ed771c1811",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0e43a41c-5daa-4e34-ae5a-aa4f7507766c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "aac27335-51e6-474e-a7a3-3fe8d1c612d6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "08ceb3d3-b7b7-4e62-a1d5-7515b38e96bc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "93a2a203-54d1-47d4-8247-344e28d9763a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f0a6e80e-9714-4ca3-be1c-e0d27578b940",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5be0a858-a118-4ed5-b5f3-244184bd941d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c4d9877e-86a7-4943-b902-e71cbe559935",
                "ordinal": 3
              }
            ],
            "lineageTag": "27b36120-8bf8-4d00-927a-43af772e6bce"
          }
        ],
        "isHidden": true,
        "lineageTag": "2973c19d-8161-4f21-87a2-1d7801c0afcf",
        "partitions": [
          {
            "name": "LocalDateTable_1ed80c1e-62ce-4830-b5cb-584a3e26f927",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Orders'[Ship Date])), 1, 1), Date(Year(MAX('Orders'[Ship Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Returns",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "617dd3fa-6185-4f77-913e-edc36b7f8411",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddf9be8a-ccd1-4492-9f93-311c302ecf1b",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "22b39a70-4d70-49e7-8184-cc99ed28329b",
        "partitions": [
          {
            "name": "Returns",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\USER\\Downloads\\Power BI Exercise Files\\Sample Superstore.xlsx\"), null, true),",
                "    Returns_Sheet = Source{[Item=\"Returns\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Returns_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order ID\", Int64.Type}, {\"Status\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Manegers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fed5085-112b-43c2-ad7f-d83ab7c67335",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Manager first",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9af09db-7c23-4766-ac68-1e47baa89ec8",
            "sourceColumn": "Manager first",
            "summarizeBy": "none"
          },
          {
            "name": "Manager last",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f4d7dd8-a55f-4370-b21f-56fe817668c9",
            "sourceColumn": "Manager last",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "85299147-7ba8-4fd5-82c5-0356e3242a65",
        "partitions": [
          {
            "name": "Manegers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\USER\\Downloads\\Power BI Exercise Files\\Sample Superstore.xlsx\"), null, true),",
                "    Users_Sheet = Source{[Item=\"Users\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Users_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Region\", type text}, {\"Manager\", type text}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type1\", \"Manager\", \"Manager - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Manager\", \"Manager first\"}, {\"Manager - Copy\", \"Manager last\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"Chris\",\"Evans\",Replacer.ReplaceText,{\"Manager last\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Erin\",\"Rogers\",Replacer.ReplaceText,{\"Manager last\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Sam\",\"Evans\",Replacer.ReplaceText,{\"Manager last\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"William\",\"Rogers\",Replacer.ReplaceText,{\"Manager last\"})",
                "in",
                "    #\"Replaced Value3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "orders by region",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "719f2bdf-c493-484c-8e1b-1e130264ce38",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "bbc069d6-6c06-41a0-97cb-c121e18b3bd5",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "b07c8034-033d-4a96-9620-506e68c03773",
            "sourceColumn": "Shipping Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1f494ca-a6e7-4b56-ae1d-c3956264cbb4",
            "sourceColumn": "Customer ID",
            "summarizeBy": "count"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "acfc9e04-2710-4825-babb-4716653e5ff5",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c869b2fa-7f61-4ad0-97ce-2c24999c2599",
            "sourceColumn": "Ship Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3afaa0a2-abd5-48ee-842f-47d6ab2b58cd",
            "sourceColumn": "Customer Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "43fd9416-83d1-4f09-9186-ff23fa15084d",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f10122c6-603f-4305-9d99-b1a24462214a",
            "sourceColumn": "Product Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Container",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "738a8245-e838-4983-ab89-3231d9d9b6f3",
            "sourceColumn": "Product Container",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0ffb27d3-3cc0-4d67-9f5b-a88b7ccea61a",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3b852714-569e-464e-87a7-5aa575f0b99f",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4ca19d90-5fb1-4cab-ba20-2a19ef8872c1",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f6c8826a-ab40-4b27-a869-82b4415d96ea",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "09160869-4c2e-4459-b400-b0756ad9cd08",
            "sourceColumn": "Postal Code",
            "summarizeBy": "count"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "76d03832-c97e-4f5a-abfc-6414d3648156",
            "sourceColumn": "Order Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_05447a49-6a11-4d7a-b5c2-9344940f2fdd"
                },
                "isDefault": true,
                "relationship": "fcd3fee3-fb66-40c0-a217-60a24761b81d"
              }
            ]
          },
          {
            "name": "Ship Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "a41b265c-269e-44dd-b62d-abe48f17494b",
            "sourceColumn": "Ship Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_aa0949e3-1ac4-42a9-93c5-098404b2560b"
                },
                "isDefault": true,
                "relationship": "1d455758-9a79-4bec-83e9-e84f847f14ba"
              }
            ]
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "2ef28fe6-2387-4554-afb9-d02f194ad951",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "b1a0f5fb-c232-4191-9d4c-d4be6bdddb87",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7503d5a3-888d-400b-b859-cc8ac504aea7",
            "sourceColumn": "Order ID",
            "summarizeBy": "count"
          },
          {
            "name": "Manegers.Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "07831141-ccbf-46f4-a300-353d66debf5e",
            "sourceColumn": "Manegers.Region",
            "summarizeBy": "none"
          },
          {
            "name": "Manegers.Manager first",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "141234fa-d5a3-4d79-a862-d3181bc0cb59",
            "sourceColumn": "Manegers.Manager first",
            "summarizeBy": "none"
          },
          {
            "name": "Manegers.Manager last",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "934573cd-084b-4b98-a4c6-5e8c689a1208",
            "sourceColumn": "Manegers.Manager last",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "9c5da9cc-3900-4d07-ad3a-e1187bf88fa1",
        "partitions": [
          {
            "name": "orders by region",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.NestedJoin(Orders, {\"Region\"}, Manegers, {\"Region\"}, \"Manegers\", JoinKind.RightOuter),",
                "    #\"Expanded Manegers\" = Table.ExpandTableColumn(Source, \"Manegers\", {\"Region\", \"Manager first\", \"Manager last\"}, {\"Manegers.Region\", \"Manegers.Manager first\", \"Manegers.Manager last\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Expanded Manegers\",{{\"Manegers.Region\", Order.Ascending}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Sorted Rows\", each ([Manegers.Region] <> \"Central\")),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Filtered Rows\",{{\"Manegers.Region\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_05447a49-6a11-4d7a-b5c2-9344940f2fdd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3df45c9f-5270-4c80-950a-a7708ca368bf",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "75ff6a3c-9a14-4c48-a4f0-3eac63431415",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6a5c980e-b04e-4406-b0cd-1de11167626c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7fa42a0a-a843-4138-afc6-948602556da0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5607c181-01f2-421b-9586-713d161a0e52",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f355a27a-43a5-4516-a902-aed52fed92fc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "79f55fa4-59cb-495c-bbe1-44902ec7bd72",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7d359d97-5002-43fa-b867-490b21204840",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b0525cb9-8264-4d27-9114-c7dab82aed55",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7363592e-fe8f-4bfc-b5fa-de06847d9454",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2b2ef595-accd-4187-8594-eea9d5796384",
                "ordinal": 3
              }
            ],
            "lineageTag": "402a84c5-adc5-4f7b-a4d3-0c750820a71a"
          }
        ],
        "isHidden": true,
        "lineageTag": "86aae884-e34c-4117-9529-2bcbf8f7016a",
        "partitions": [
          {
            "name": "LocalDateTable_05447a49-6a11-4d7a-b5c2-9344940f2fdd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders by region'[Order Date])), 1, 1), Date(Year(MAX('orders by region'[Order Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_aa0949e3-1ac4-42a9-93c5-098404b2560b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "206b207d-c373-43e5-89b2-820b6a819d69",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d12047ac-a4b2-47e5-8270-1b12947cc672",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c4ff3e43-c6f6-4d0d-ab23-55e2eabbbee5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d41fe754-36df-498f-8986-4807f946691b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8102fac9-b220-47a2-8207-ea804d92960e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c17deecb-95c0-486b-84a0-21d1182cafbb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "01869a10-6fb6-4bea-9075-6b53e00cec6c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2258eae3-4a99-40cc-9904-275f971f3d34",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0d00820f-239a-4c9f-b565-c854aee35fd7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "140c6607-b2b1-439e-9de3-c544141bad98",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "92379c47-94e3-407d-be82-ed61765f69b1",
                "ordinal": 3
              }
            ],
            "lineageTag": "85c62ed1-3d5d-47ca-84a4-89910d75f2e0"
          }
        ],
        "isHidden": true,
        "lineageTag": "f34edd0c-068d-4c38-86af-62d1f267eb6d",
        "partitions": [
          {
            "name": "LocalDateTable_aa0949e3-1ac4-42a9-93c5-098404b2560b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders by region'[Ship Date])), 1, 1), Date(Year(MAX('orders by region'[Ship Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dim Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          },
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3c45f20c-39f3-4ce6-8957-c155d49d575d",
            "sourceColumn": "Customer ID",
            "summarizeBy": "count"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d2d747b5-cc0a-4f49-8244-f88573ddfaf9",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "25dfc341-5e33-4fa1-ae27-4c109cb8c2c6",
            "sourceColumn": "Customer Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9dc09794-10fc-4f64-8d06-228dfb8e3592",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bd2ceda0-5d46-48e6-a5ab-706642de6aa3",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f2e52d03-c6c0-4c94-b7b7-caaa43ecba7d",
            "sourceColumn": "Postal Code",
            "summarizeBy": "count"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "467eb34b-6372-45c2-8668-4dd40833d87c",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "d3f48b64-ca3b-4137-8383-9d9129d2b5bf",
        "partitions": [
          {
            "name": "Dim Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\USER\\Downloads\\Power BI Exercise Files\\Sample Superstore.xlsx\"), null, true),",
                "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Row ID\", Int64.Type}, {\"Order Priority\", type text}, {\"Discount\", type number}, {\"Unit Price\", type number}, {\"Shipping Cost\", type number}, {\"Customer ID\", Int64.Type}, {\"Customer Name\", type text}, {\"Ship Mode\", type text}, {\"Customer Segment\", type text}, {\"Product Category\", type text}, {\"Product Sub-Category\", type text}, {\"Product Container\", type text}, {\"Product Name\", type text}, {\"Product Base Margin\", type number}, {\"Region\", type text}, {\"State or Province\", type text}, {\"City\", type text}, {\"Postal Code\", Int64.Type}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Profit\", type number}, {\"Quantity ordered new\", Int64.Type}, {\"Sales\", type number}, {\"Order ID\", Int64.Type}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Discount\", \"Unit Price\", \"Shipping Cost\", \"Customer ID\", \"Customer Name\", \"Ship Mode\", \"Customer Segment\", \"Product Category\", \"Product Sub-Category\", \"Product Container\", \"Product Name\", \"Region\", \"State or Province\", \"City\", \"Postal Code\", \"Order Date\", \"Ship Date\", \"Profit\", \"Sales\", \"Order ID\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([State or Province] = \"Arizona\" or [State or Province] = \"California\" or [State or Province] = \"Florida\" or [State or Province] = \"New Jersey\" or [State or Province] = \"New York\")),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Filtered Rows\",{{\"State or Province\", Order.Ascending}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Sorted Rows\",{{\"State or Province\", \"State\"}}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns\",{\"Discount\", \"Customer ID\", \"Customer Name\", \"Customer Segment\", \"Region\", \"City\", \"Postal Code\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns1\",{\"Customer ID\", \"Customer Name\", \"Customer Segment\", \"Region\", \"City\", \"Postal Code\", \"Discount\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Product",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          },
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Produck id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3492aa0c-cfa2-480f-a072-92a3e73f8f42",
            "sourceColumn": "Produck id",
            "summarizeBy": "sum"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b06ef52a-0f36-40b9-99ee-b52154e29bd4",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7910c2b7-cc9b-4a1c-8c6c-1c959ca2e5e0",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e3e9afa2-e31d-402d-a460-3c64a8748936",
            "sourceColumn": "Product Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Container",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "74fb7663-967c-4232-a695-7250850a179a",
            "sourceColumn": "Product Container",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4cee3298-784b-49ae-b3d2-602a05f21c5a",
        "partitions": [
          {
            "name": "Dim Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\USER\\Downloads\\Power BI Exercise Files\\Sample Superstore.xlsx\"), null, true),",
                "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Row ID\", Int64.Type}, {\"Order Priority\", type text}, {\"Discount\", type number}, {\"Unit Price\", type number}, {\"Shipping Cost\", type number}, {\"Customer ID\", Int64.Type}, {\"Customer Name\", type text}, {\"Ship Mode\", type text}, {\"Customer Segment\", type text}, {\"Product Category\", type text}, {\"Product Sub-Category\", type text}, {\"Product Container\", type text}, {\"Product Name\", type text}, {\"Product Base Margin\", type number}, {\"Region\", type text}, {\"State or Province\", type text}, {\"City\", type text}, {\"Postal Code\", Int64.Type}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Profit\", type number}, {\"Quantity ordered new\", Int64.Type}, {\"Sales\", type number}, {\"Order ID\", Int64.Type}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Discount\", \"Unit Price\", \"Shipping Cost\", \"Customer ID\", \"Customer Name\", \"Ship Mode\", \"Customer Segment\", \"Product Category\", \"Product Sub-Category\", \"Product Container\", \"Product Name\", \"Region\", \"State or Province\", \"City\", \"Postal Code\", \"Order Date\", \"Ship Date\", \"Profit\", \"Sales\", \"Order ID\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([State or Province] = \"Arizona\" or [State or Province] = \"California\" or [State or Province] = \"Florida\" or [State or Province] = \"New Jersey\" or [State or Province] = \"New York\")),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Filtered Rows\",{{\"State or Province\", Order.Ascending}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Sorted Rows\",{{\"State or Province\", \"State\"}}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns\",{\"Product Category\", \"Product Sub-Category\", \"Product Container\", \"Product Name\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns1\",{\"Product Name\", \"Product Category\", \"Product Sub-Category\", \"Product Container\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Reordered Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"Product Name\", \"Product Category\", \"Product Sub-Category\", \"Product Container\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"Index\", \"Produck id\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}